# Generated by Django 4.2.4 on 2023-08-12 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dept',
            new_name='department',
        ),
    ]
