# Generated by Django 4.2.4 on 2023-08-12 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_rename_dept_user_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Meeting date')),
                ('recording', models.FileField(upload_to='meetings', verbose_name='Meeting recording')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.village')),
            ],
        ),
    ]
