# Generated by Django 4.2.4 on 2023-08-12 14:16

from django.db import migrations, models
import feedback.models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_meeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='recording',
            field=models.FileField(upload_to='meetings', validators=[feedback.models.validate_video], verbose_name='Meeting recording'),
        ),
    ]
