# Generated by Django 4.2.4 on 2023-08-12 15:07

from django.db import migrations, models
import django.db.models.deletion
import feedback.models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_remove_user_username_alter_meeting_recording'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='suggestions', validators=[feedback.models.validate_audio], verbose_name='Meeting suggestion')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.meeting')),
            ],
        ),
    ]
