# Generated by Django 4.2.4 on 2023-08-12 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_meetingsuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingsuggestion',
            name='made_by',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
