# Generated by Django 4.2.4 on 2023-08-12 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_meetingsuggestion_made_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.village'),
        ),
    ]
